version: '3.7'

services:
  api:
    build: .
    container_name: api
    env_file: .env
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:8000
    command: [ "gunicorn", "-w", "3", "app.wsgi", "-b", ":8000" ]
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=manatal_user
      - POSTGRES_PASSWORD=manatal_pass
      - POSTGRES_DB=manatal
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
